### ISSUE TITLE
Dynamic size containers

### ISSUE THREAD

**Issue by matthieu637** [e-/ANN#2]
Hello,
I would like to use your library in an online scenario, but I can't find an example where the datasource don't have a fixed size.

How to add more data to an ArrayDataSource after having computed some nearest neighbors on the current data ?
Using the .run on ProgressiveKDTreeIndex only parses new points from the current fixed size ArrayDataSource.

**Comment by e-** [comment]
You need to implement a data source that reads some rows incrementally.
A DataSource has two methods to indicate the number of rows: `size()` for the number of rows that have already been loaded and `capacity()` for the maximum number of rows that it can have.

In the current implementation, we only have data sources that have all the rows when initialized, so `ds.size()` is always equal to `ds.capacity()`. You need to implement your own data source overriding the `size()` and `capacity()` methods. You may want to additionally implement a method like `load(int t)` which reads `t` rows from the disk and call it with a tree's `run()` method alternately. 

Please note that `size()` can be changed during execution but `capacity()` is not. If the maximum number of incoming rows is unknown, you can set the capacity to a sufficiently large number.

**Comment by matthieu637** [comment]
Thanks it worked, I did a kind of DequeDataSource.

If it interests someone else: https://github.com/matthieu637/ddrl/blob/lipschitz-cnfac/agent/cacla/include/panene/data_source/array_data_source.h
