### ISSUE TITLE
Installation fails at "make" step

### ISSUE THREAD

**Issue by Mahog** [e-/ANN#6]
I am trying to build PANENE to use it within [progressive-umap](https://github.com/hyungkwonko/progressive-umap). I was able to follow the build instructions up until the step were we run ```make``` to build PANENE. This step fails with the following error message (from 57% into the process):

```make
[...]
g++ -pthread -shared -B /[...]/miniconda3/compiler_compat -L/[...]/miniconda3/lib -Wl,-rpath=/[...]/miniconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/[...]/Development/PANENE/python/pynene.o -o build/lib.linux-x86_64-3.7/pynene.cpython-37m-x86_64-linux-gnu.so -lpanene -std=c++11 -fopenmp

/[...]/miniconda3/compiler_compat/ld: cannot find -lpanene
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
python/CMakeFiles/target.dir/build.make:60: recipe for target 'python/build/timestamp' failed
make[2]: *** [python/build/timestamp] Error 1
CMakeFiles/Makefile2:367: recipe for target 'python/CMakeFiles/target.dir/all' failed
make[1]: *** [python/CMakeFiles/target.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

I am running  ```Python 3.6.5``` and ```3.8.5```, ```g++ 7.5.0```, ```make 4.1``` and ```cmake 3.10.2``` and have run into this error on the following platforms:
- Ubuntu 16.04.7 on Linux 4.15.0-122-generic
- Ubuntu 18.04.4 LTS on Linux 4.15.0-122-generic
- Linux subsystem for Windows with Ubuntu 18.04.5 LTS on Linux 4.4.0-18362.

Any ideas on how to fix this?

**Comment by hyungkwonko** [comment]
As far as I remember, this is not related to the system/library version. You may refer to [this](https://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary/34256630).
Hope it helps.

**Comment by Mahog** [comment]
Thank you for that link, it did the trick for me. To make g++ aware of ```-lpanene```, I changed line 6 in [python/setup.py.in](https://github.com/e-/PANENE/blob/master/python/setup.py.in) to this (basically including a link to the libs in the build directory):
```
extra_link_args = ["-lpanene", "-L${CMAKE_CURRENT_SOURCE_DIR}/build/"] 
```

**Comment by Mahog** [comment]
I don't know how "portable" this solution is (given the comment that is already in that file). Let me know if you are interested in a PR for this.
